### ISSUE TITLE
Missing files in release file 

### ISSUE THREAD

**Issue by derjoern** [PluginsOCSInventory-NG/runningDatabaseInstances#1]
Hi!

The release file seems to lack files namely all directories are empty and README.md is missing.

**Comment by DTeubner** [comment]
Hi guys,
I found the same and so I cannot use the plugin manager to install it. Even filling missing files from git repo did not solve it.

Cheers
Daniel

**Comment by gillesdubois** [comment]
A new release will be created soon with the problem fixed.

Regards,
Gilles Dubois.
