### ISSUE TITLE
Problem Instalation Plugin

### ISSUE THREAD

**Issue by ghost** [PluginsOCSInventory-NG/runningDatabaseInstances#10]
Hi,

When I try to install the plugin, OCS give me an error and told me it's an invalid plugin. Can you help me with that please ?

Thanks 
!

=========================================

Bonjour,

Je ne parviens pas a installer le plugin : Running Database Instances j'ai le message d'erreur ci-dessous qui s'affiche :

ERREUR: runningDatabaseInstances est un plugin non valide, vérifiez vos sources.
Installation annulée !

Pouvez-vous m'aider avec ce problème ?

![image](https://s1.picsriver.com/2018/09/17/image.png)

Merci

**Comment by gillesdubois** [comment]
Bonjour,

Ces problèmes ont été corrigé avec la version 2.7 d'OCS Inventory.

Cordialement,
Gilles Dubois.
