### ISSUE TITLE
Please add support for sql server 2019

### ISSUE THREAD

**Issue by pchamorro2005** [PluginsOCSInventory-NG/runningDatabaseInstances#16]
Please add support for sql server 2019. I think these lines are the ones needed to be inserted (lines 170 and 288):

                            If strSQLFileVersion = 150 Then strWMIsql = "ComputerManagement15"

                            ElseIf Left(strVersion,2) = "15" Then
                                strSQLName = "Microsoft SQL Server 2019"

Thank you

**Comment by pchamorro2005** [comment]
I added also:

`If strSQLFileVersion = 131 Then strWMIsql = "ComputerManagement13"`

because I realized some SQL Databases queries return that version.

**Comment by gillesdubois** [comment]
Hi,

Could you use the powershell script ?
We don't maintain the VBS one anymore.

Regards,
Gilles.

**Comment by pchamorro2005** [comment]
Hi, 

1. First, I think there is an error in the label VERSION_NAME because in the .vbs script that label doesn't exist:

The vbs script includes:

```
                            Result = "<DBINSTANCES>" & VbCrLf
                            Result = Result & "<PUBLISHER>Microsoft Corporation</PUBLISHER>" & VbCrLf
                            Result = Result & "<NAME>" & strSQLName & strServicePack & "</NAME>" & VbCrLf
                            Result = Result & "<VERSION>" & strVersion & "</VERSION>" & VbCrLf
                            Result = Result & "<EDITION>" & strEdition & "</EDITION>" & VbCrLf
                            Result = Result & "<INSTANCE>" & strServiceName & "</INSTANCE>" & VbCrLf
                            Result = Result & "</DBINSTANCES>"
```

And the .ps1 script includes:

```
       $xml += "<DBINSTANCES>"
       $xml += "<PUBLISHER>Microsoft Corporation</PUBLISHER>"
       $xml += "<VERSION_NAME>" + $serverName + "</VERSION_NAME>"
       $xml += "<VERSION>" + $version + "</VERSION>"
       $xml += "<EDITION>" + $edition + "</EDITION>"
       $xml += "<INSTANCE>" + $instanceName + "</INSTANCE>"
       $xml += "</DBINSTANCES>"
```
Am I right?
