### ISSUE TITLE
Problem Instalation Plugin

### ISSUE THREAD

**Issue by ekip-94** [PluginsOCSInventory-NG/runningDatabaseInstances#8]
When I try to install the plugin, OCS give me an error and told me it's an invalid plugin. Can someone help me with that please

**Comment by steph78630** [comment]
Hi,

for this issue, see the best answer at : http://ask.ocsinventory-ng.org/8747/scheduledtasks-plugins-not-visible?show=8762#a8762

Regards, Stéphane

**Comment by aze789** [comment]
Merci pour la réponse mais comment je supprimer le dossier du fichier zip ??
