### ISSUE TITLE
Fichier Manquant

### ISSUE THREAD

**Issue by ekip-94** [PluginsOCSInventory-NG/runningDatabaseInstances#9]
Bonjour,
je ne peut pas installer le plugin car il manque les fichier Map.pm et runningDatabase.conf

une solution à mon problème ?

**Comment by steph78630** [comment]
Bonjour,

problème fréquemment rencontré, la solution est détaillée dans une précédente demande que vous nous avez fait.

> Créer les dossiers + copie des fichiers Map.pm + .conf manuellement.

**Comment by ekip-94** [comment]
mais le probleme c'est que je ne peut pas installer le fichier zip sur OCS

**Comment by steph78630** [comment]
je vous propose de créer une demande sur https://ask.ocsinventory-ng.org ou vous aurez davantage de support.

**Comment by aze789** [comment]
Bonjour,
J'ai essayer de poser la question sur ce site mais lorsque je veux me créer un compte il y'a une sort de captcha qui me demande "What is the main function of OCS Inventory NG?" 
Une idée de la réponse svp ?
